[config]
reload_apps = true
set_wallpaper = false

[config.reload_apps_list]
dunst = true

[templates.hyprland]
input_path = '~/.config/matugen/template/hyprland.template'
output_path = '~/.cache/matugen/colors-hyprland.conf'

[templates.rofi]
input_path = '~/.config/matugen/template/rofi.template'
output_path = '~/.cache/matugen/colors.rasi'

[templates.css]
input_path = '~/.config/matugen/template/css.template'
output_path = '~/.cache/matugen/colors.css'

[templates.scss]
input_path = '~/.config/matugen/template/scss.template'
output_path = '~/.cache/matugen/colors.scss'
