-- Config
require('user.core.autocmd')
require('user.core.colors')
require('user.core.keymaps')
require('user.core.options')
require('user.plugins.bufferline')
require('user.plugins.cmp')
require('user.plugins.gitsigns')
require('user.plugins.lsp')
require('user.plugins.null-ls')
require('user.plugins.tree')
