-- Core
require('user.core.autocmd')
require('user.core.colors')
require('user.core.lspconfig')
require('user.core.keymaps')
require('user.core.options')

-- Plugins
require('user.plugins.alpha-nvim')
require('user.plugins.autopairs')
require('user.plugins.bufferline')
require('user.plugins.gitsigns')
require('user.plugins.indent-blankline')
require('user.plugins.lsp_lines')
require('user.plugins.lspsaga')
require('user.plugins.lualine')
require('user.plugins.luasnip')
require('user.plugins.mason')
require('user.plugins.mason-nvim-dap')
require('user.plugins.null-ls')
require('user.plugins.nvim-cmp')
require('user.plugins.nvim-dap')
require('user.plugins.nvim-dap-ui')
require('user.plugins.nvim-dap-python')
require('user.plugins.nvim-dap-vtxt')
require('user.plugins.nvim-tree')
require('user.plugins.packer')
require('user.plugins.py_lsp')
require('user.plugins.telescope')
require('user.plugins.treesitter')
require('user.plugins.which-key')
