# TTY1 (Wayland)
if [[ "$(tty)" = "/dev/tty1" ]]; then
  hyprland
  # qtile start -b wayland
fi

# TTY2 (X11)
if [[ "$(tty)" = "/dev/tty2" ]]; then
  pgrep qtile || startx "${XDG_CONFIG_HOME}/x11/.xinitrc"
fi
