#!/usr/bin/env bash

if [ $# -eq 0 ]; then
  echo ":: Please provide an argument"
  exit 1
fi

case $1 in
  --up)
    wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 10%+
    ;;
  --down)
    wpctl set-volume -l 1.5 @DEFAULT_AUDIO_SINK@ 10%-
    ;;
  --toggle)
    wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    ;;
  *)
    echo ":: [-] Unknown argument '$1'."
    exit 1
    ;;
esac
