# Prompt order
SPACESHIP_PROMPT_ORDER=(
  time          # Time stampts section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  hg            # Mercurial section (hg_branch  + hg_status)
  package       # Package version
  node          # Node.js section
  ruby          # Ruby section
  elm           # Elm section
  elixir        # Elixir section
  xcode         # Xcode section
  swift         # Swift section
  golang        # Go section
  php           # PHP section
  rust          # Rust section
  haskell       # Haskell Stack section
  julia         # Julia section
  docker        # Docker section
  aws           # Amazon Web Services section
  gcloud        # Google Cloud Platform section
  venv          # virtualenv section
  conda         # conda virtualenv section
  dotnet        # .NET section
  kubectl       # Kubectl context section
  terraform     # Terraform workspace section
  ibmcloud      # IBM Cloud section
  exec_time     # Execution time
  line_sep      # Line break
  battery       # Battery level and status
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

# Prompt
SPACESHIP_PROMPT_ADD_NEWLINE=true
SPACESHIP_PROMPT_SEPARATE_LINE=false
#SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=false
#SPACESHIP_PROMPT_PREFIXES_SHOW=true
#SPACESHIP_PROMPT_SUFFIXES_SHOW=true
#SPACESHIP_PROMPT_DEFAULT_PREFIX='via '
#SPACESHIP_PROMPT_DEFAULT_SUFFIX=" "

# Char
#SPACESHIP_CHAR_PREFIX=""
#SPACESHIP_CHAR_SUFFIX
#SPACESHIP_CHAR_SYMBOL
#SPACESHIP_CHAR_SYMBOL_ROOT
#SPACESHIP_CHAR_SYMBOL_SECONDARY
#SPACESHIP_CHAR_COLOR_SUCCESS
#SPACESHIP_CHAR_COLOR_FAILURE
#SPACESHIP_CHAR_COLOR_SECONDARY

# Time
SPACESHIP_TIME_SHOW='false'
#SPACESHIP_TIME_PREFIX
#SPACESHIP_TIME_SUFFIX
#SPACESHIP_TIME_COLOR
#SPACESHIP_TIME_FORMAT
#SPACESHIP_TIME_12HR

# User
SPACESHIP_USER_SHOW="true"
#SPACESHIP_USER_SHOW
#SPACESHIP_USER_PREFIX
#SPACESHIP_USER_SUFFIX
#SPACESHIP_USER_COLOR
#SPACESHIP_USER_COLOR_ROOT

# Host
SPACESHIP_HOST_SHOW="true"
#SPACESHIP_HOST_SHOW_FULL
#SPACESHIP_HOST_PREFIX
#SPACESHIP_HOST_SUFFIX
#SPACESHIP_HOST_COLOR
#SPACESHIP_HOST_COLOR_SSH

# Directory
SPACESHIP_DIR_SHOW="true"
#SPACESHIP_DIR_PREFIX="in "
#SPACESHIP_DIR_SUFFIX
#SPACESHIP_DIR_TRUNC
#SPACESHIP_DIR_TRUNC_PREFIX
#SPACESHIP_DIR_TRUNC_REPO
#SPACESHIP_DIR_COLOR
#SPACESHIP_DIR_LOCK_SYMBOL
#SPACESHIP_DIR_LOCK_COLOR

# Git
#SPACESHIP_GIT_SHOW=true
#SPACESHIP_GIT_PREFIX="on "
#SPACESHIP_GIT_SUFFIX=$SPACESHIP_PROMPT_DEFAULT_SUFFIX
#SPACESHIP_GIT_SYMBOL

# Git branch
#SPACESHIP_GIT_BRANCH_SHOW
#SPACESHIP_GIT_BRANCH_PREFIX
#SPACESHIP_GIT_BRANCH_SUFFIX
#SPACESHIP_GIT_BRANCH_COLOR

# Git status
#PACESHIP_GIT_STATUS_SHOW
#SPACESHIP_GIT_STATUS_PREFIX
#SPACESHIP_GIT_STATUS_SUFFIX
#SPACESHIP_GIT_STATUS_COLOR
#SPACESHIP_GIT_STATUS_UNTRACKED
#SPACESHIP_GIT_STATUS_ADDED
#SPACESHIP_GIT_STATUS_MODIFIED
#SPACESHIP_GIT_STATUS_RENAMED
#SPACESHIP_GIT_STATUS_DELETED
#SPACESHIP_GIT_STATUS_STASHED
#SPACESHIP_GIT_STATUS_UNMERGED
#SPACESHIP_GIT_STATUS_AHEAD
#SPACESHIP_GIT_STATUS_BEHIND
#SPACESHIP_GIT_STATUS_DIVERGED

# Package version
#SPACESHIP_PACKAGE_SHOW
#SPACESHIP_PACKAGE_PREFIX
#SPACESHIP_PACKAGE_SUFFIX  $SPACESHIP_PROMPT_DEFAULT_SUFFIX
#SPACESHIP_PACKAGE_SYMBOL
#SPACESHIP_PACKAGE_COLOR

# Node.js
#SPACESHIP_NODE_SHOW
#SPACESHIP_NODE_PREFIX
#SPACESHIP_NODE_SUFFIX
#SPACESHIP_NODE_SYMBOL
#SPACESHIP_NODE_DEFAULT_VERSION
#SPACESHIP_NODE_COLOR

# Ruby
#SPACESHIP_RUBY_SHOW
#SPACESHIP_RUBY_PREFIX
#SPACESHIP_RUBY_SUFFIX
#SPACESHIP_RUBY_SYMBOL
#SPACESHIP_RUBY_COLOR

# Elm
#SPACESHIP_ELM_SHOW
#SPACESHIP_ELM_PREFIX
#SPACESHIP_ELM_SUFFIX
#SPACESHIP_ELM_SYMBOL
#SPACESHIP_ELM_COLOR

# Elixir
#SPACESHIP_ELIXIR_SHOW
#SPACESHIP_ELIXIR_PREFIX
#SPACESHIP_ELIXIR_SUFFIX
#SPACESHIP_ELIXIR_DEFAULT_VERSION
#SPACESHIP_ELIXIR_SYMBOL
#SPACESHIP_ELIXIR_COLOR

# Xcode
#SPACESHIP_XCODE_SHOW_LOCAL
#SPACESHIP_XCODE_SHOW_GLOBAL
#SPACESHIP_XCODE_PREFIX
#SPACESHIP_XCODE_SUFFIX
#SPACESHIP_XCODE_SYMBOL
#SPACESHIP_XCODE_COLOR

# Swift
#SPACESHIP_SWIFT_SHOW_LOCAL
#SPACESHIP_SWIFT_SHOW_GLOBAL
#SPACESHIP_SWIFT_PREFIX
#SPACESHIP_SWIFT_SUFFIX
#SPACESHIP_SWIFT_SYMBOL
#SPACESHIP_SWIFT_COLOR

# Go
#SPACESHIP_GOLANG_SHOW
#SPACESHIP_GOLANG_PREFIX
#SPACESHIP_GOLANG_SUFFIX
#SPACESHIP_GOLANG_SYMBOL
#SPACESHIP_GOLANG_COLOR

# PHP
#SPACESHIP_PHP_SHOW
#SPACESHIP_PHP_PREFIX
#SPACESHIP_PHP_SUFFIX
#SPACESHIP_PHP_SYMBOL
#SPACESHIP_PHP_COLOR

# Rust
#SPACESHIP_RUST_SHOW
#SPACESHIP_RUST_PREFIX
#SPACESHIP_RUST_SUFFIX
#SPACESHIP_RUST_SYMBOL
#SPACESHIP_RUST_COLOR
#SPACESHIP_RUST_VERBOSE_VERSION

# Haskell
#SPACESHIP_HASKELL_SHOW
#SPACESHIP_HASKELL_PREFIX
#SPACESHIP_HASKELL_SUFFIX
#SPACESHIP_HASKELL_SYMBOL
#SPACESHIP_HASKELL_COLOR

# Julia
#SPACESHIP_JULIA_SHOW
#SPACESHIP_JULIA_PREFIX
#SPACESHIP_JULIA_SUFFIX
#SPACESHIP_JULIA_SYMBOL
#SPACESHIP_JULIA_COLOR

# Docker
#SPACESHIP_DOCKER_SHOW
#SPACESHIP_DOCKER_PREFIX
#SPACESHIP_DOCKER_SUFFIX
#SPACESHIP_DOCKER_SYMBOL
#SPACESHIP_DOCKER_COLOR
#SPACESHIP_DOCKER_VERBOSE

# Docker context
#SPACESHIP_DOCKER_CONTEXT_SHOW
#SPACESHIP_DOCKER_CONTEXT_PREFIX
#SPACESHIP_DOCKER_CONTEXT_SUFFIX

# AWS
#SPACESHIP_AWS_SHOW
#SPACESHIP_AWS_PREFIX
#SPACESHIP_AWS_SUFFIX
#SPACESHIP_AWS_SYMBOL
#SPACESHIP_AWS_COLOR

# Google Cloud Platform
#SPACESHIP_GCLOUD_SHOW
#SPACESHIP_GCLOUD_PREFIX
#SPACESHIP_GCLOUD_SUFFIX
#SPACESHIP_GCLOUD_SYMBOL
#SPACESHIP_GCLOUD_COLOR

# Virtualenv
#SPACESHIP_VENV_SHOW
#SPACESHIP_VENV_PREFIX
#SPACESHIP_VENV_SUFFIX
#SPACESHIP_VENV_SYMBOL
#SPACESHIP_VENV_GENERIC_NAMES
#SPACESHIP_VENV_COLOR

# Conda virtualenv
#SPACESHIP_CONDA_SHOW
#SPACESHIP_CONDA_PREFIX
#SPACESHIP_CONDA_SUFFIX
#SPACESHIP_CONDA_SYMBOL
#SPACESHIP_CONDA_COLOR
#SPACESHIP_CONDA_VERBOSE

# .NET
#SPACESHIP_DOTNET_SHOW
#SPACESHIP_DOTNET_PREFIX
#SPACESHIP_DOTNET_SUFFIX
#SPACESHIP_DOTNET_SYMBOL
#SPACESHIP_DOTNET_COLOR

# Kubernetes
#SPACESHIP_KUBECTL_SHOW
#SPACESHIP_KUBECTL_PREFIX
#SPACESHIP_KUBECTL_SUFFIX
#SPACESHIP_KUBECTL_COLOR
#SPACESHIP_KUBECTL_SYMBOL

# Kubernetes version
#SPACESHIP_KUBECTL_VERSION_SHOW
#SPACESHIP_KUBECTL_VERSION_PREFIX
#SPACESHIP_KUBECTL_VERSION_SUFFIX
#SPACESHIP_KUBECTL_VERSION_COLOR

# Kubernetes context
#SPACESHIP_KUBECONTEXT_SHOW
#SPACESHIP_KUBECONTEXT_PREFIX
#SPACESHIP_KUBECONTEXT_SUFFIX
#SPACESHIP_KUBECONTEXT_COLOR
#SPACESHIP_KUBECONTEXT_NAMESPACE_SHOW
#SPACESHIP_KUBECONTEXT_COLOR_GROUPS

# Terraform workspace
#SPACESHIP_TERRAFORM_SHOW
#SPACESHIP_TERRAFORM_PREFIX
#SPACESHIP_TERRAFORM_SUFFIX
#SPACESHIP_TERRAFORM_SYMBOL
#SPACESHIP_TERRAFORM_COLOR

# IBM Cloud
#SPACESHIP_IBMCLOUD_SHOW
#SPACESHIP_IBMCLOUD_PREFIX
#SPACESHIP_IBMCLOUD_SUFFIX
#SPACESHIP_IBMCLOUD_SYMBOL
#SPACESHIP_IBMCLOUD_COLOR

# Execution time
#SPACESHIP_EXEC_TIME_SHOW
#SPACESHIP_EXEC_TIME_PREFIX
#SPACESHIP_EXEC_TIME_SUFFIX
#SPACESHIP_EXEC_TIME_COLOR
#SPACESHIP_EXEC_TIME_ELAPSED

# Battery
#SPACESHIP_BATTERY_SHOW
#SPACESHIP_BATTERY_PREFIX
#SPACESHIP_BATTERY_SUFFIX
#SPACESHIP_BATTERY_SYMBOL_CHARGING
#SPACESHIP_BATTERY_SYMBOL_DISCHARGING
#SPACESHIP_BATTERY_SYMBOL_FULL
#SPACESHIP_BATTERY_THRESHOLD

# Jobs
#SPACESHIP_JOBS_SHOW
#SPACESHIP_JOBS_PREFIX
#SPACESHIP_JOBS_SUFFIX
#SPACESHIP_JOBS_SYMBOL
#SPACESHIP_JOBS_COLOR
#SPACESHIP_JOBS_AMOUNT_PREFIX
#SPACESHIP_JOBS_AMOUNT_SUFFIX
#SPACESHIP_JOBS_AMOUNT_THRESHOLD

# Exit code
#SPACESHIP_EXIT_CODE_SHOW=true
#SPACESHIP_EXIT_CODE_PREFIX
#SPACESHIP_EXIT_CODE_SUFFIX
#SPACESHIP_EXIT_CODE_SYMBOL
#SPACESHIP_EXIT_CODE_COLOR
