[colors.primary]
background = '{background}'
foreground = '{foreground}'

[colors.cursor]
text = '{foreground}'
cursor = '{cursor}'

[colors.normal]
black   = '#000000'
red     = '#000000'
green   = '#000000'
yellow  = '#000000'
blue    = '#000000'
magenta = '#000000'
cyan    = '#000000'
white   = '#000000'

[colors.bright]
black   = '#000000'
red     = '#000000'
green   = '#000000'
yellow  = '#000000'
blue    = '#000000'
magenta = '#000000'
cyan    = '#000000'
white   = '#000000'
