-- Blink.cmp
-- https://github.com/Saghen/blink.cmp
-- https://cmp.saghen.dev/

return {
  {
  --   "saghen/blink.cmp",
  --   version = "*",
  --   event = { "InsertEnter", "CmdlineEnter" },
  --   ---@module "blink.cmp"
  --   ---@type blink.cmp.Config
  --   opts = {
  --     -- "default" for mappings similar to built-in completion
  --     -- "super-tab" for mappings similar to vscode (tab to accept, arrow keys to navigate)
  --     -- "enter" for mappings similar to "super-tab" but with "enter" to accept
  --     keymap = {
  --       preset = "default",
  --
  --       -- Accept
  --       ["<CR>"] = { "accept" },
  --       ["<C-y>"] = { "select_and_accept" },  -- default
  --       ["<CR>"] = { "accept", "fallback" },  -- enter
  --
  --       -- Documentation
  --       ["<C-b>"] = { "scroll_documentation_up", "fallback" },
  --       ["<C-f>"] = { "scroll_documentation_down", "fallback" },
  --
  --       -- Show & Hide
  --       ["<C-space>"] = { function(cmp) cmp.show({ providers = { "snippets" } }) end },
  --       ["<C-c>"] = { "hide" },
  --
  --       -- Tab
  --       ["<Tab>"]     = { "select_prev", "fallback" },
  --       ["<S-Tab>"]   = { "select_next", "fallback" },
  --
  --       ['<Tab>'] = {
  --         function(cmp)
  --           if cmp.snippet_active() then return cmp.accept()
  --           else return cmp.select_and_accept() end
  --         end,
  --         'snippet_forward',
  --         'fallback'
  --       },
  --       ['<S-Tab>'] = { 'snippet_backward', 'fallback' },
  --     },
  --
  --     appearance = {
  --       -- Sets the fallback highlight groups to nvim-cmp"s highlight groups
  --       -- Useful for when your theme doesn"t support blink.cmp
  --       -- Will be removed in a future release
  --       use_nvim_cmp_as_default = true,
  --       -- Set to "mono" for "Nerd Font Mono" or "normal" for "Nerd Font"
  --       -- Adjusts spacing to ensure icons are aligned
  --       nerd_font_variant = "mono"
  --     },
  --     snippets = { preset = "luasnip" },
  --     -- Default list of enabled providers defined so that you can extend it
  --     -- elsewhere in your config, without redefining it, due to `opts_extend`
  --     sources = {
  --       default = { "snippets", "lsp", "path", "buffer" },
  --     },
  --   },
  --   opts_extend = { "sources.default" }
  }
}
